/* Copyright 2009 Google Inc. All Rights Reserved. */ (function(){
var global=this;String.prototype.startsWith=function(prefix){return this.indexOf(prefix)==0};String.prototype.endsWith=function(suffix){var l=this.length-suffix.length;return l>=0&&this.lastIndexOf(suffix,l)==l};String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};String.prototype.subs=function(){var ret$1=this,i=0;for(;i<arguments.length;i++)ret$1=ret$1.replace(/\%s/,String(arguments[i]));return ret$1};
if(!Function.prototype.apply)Function.prototype.apply=function(oScope,opt_args){var sarg=[],rtrn,call;oScope||(oScope=global);var args=opt_args||[],i$1=0;for(;i$1<args.length;i$1++)sarg[i$1]="args["+i$1+"]";call="oScope.__applyTemp__.peek()("+sarg.join(",")+");";if(!oScope.__applyTemp__)oScope.__applyTemp__=[];oScope.__applyTemp__.push(this);rtrn=eval(call);oScope.__applyTemp__.pop();return rtrn};
if(!Array.prototype.push)Array.prototype.push=function(){var i$2=0;for(;i$2<arguments.length;i$2++)this[this.length]=arguments[i$2];return this.length};if(!Array.prototype.pop)Array.prototype.pop=function(){if(!!this.length){var val$8=this[this.length-1];this.length--;return val$8}};Array.prototype.peek=function(){return this[this.length-1]};
if(!Array.prototype.shift)Array.prototype.shift=function(){if(!(this.length==0)){var val$9=this[0],i$3=0;for(;i$3<this.length-1;i$3++)this[i$3]=this[i$3+1];this.length--;return val$9}};if(!Array.prototype.unshift)Array.prototype.unshift=function(){var numArgs=arguments.length,i$4=this.length-1;for(;i$4>=0;i$4--)this[i$4+numArgs]=this[i$4];var j=0;for(;j<numArgs;j++)this[j]=arguments[j];return this.length};
if(!Array.prototype.forEach)Array.prototype.forEach=function(callback$2,opt_scope){var i$5=0;for(;i$5<this.length;i$5++)callback$2.call(opt_scope,this[i$5],i$5,this)};
function bind(fn$2,self$1){var boundargs=fn$2.boundArgs_||[];boundargs=boundargs.concat(Array.prototype.slice.call(arguments,2));if(typeof fn$2.boundSelf_!="undefined")self$1=fn$2.boundSelf_;if(typeof fn$2.boundFn_!="undefined")fn$2=fn$2.boundFn_;var newfn=function(){var args$1=boundargs.concat(Array.prototype.slice.call(arguments));return fn$2.apply(self$1,args$1)};newfn.boundArgs_=boundargs;newfn.boundSelf_=self$1;newfn.boundFn_=fn$2;return newfn}
Function.prototype.bind=function(self$2){return bind.apply(null,[this,self$2].concat(Array.prototype.slice.call(arguments,1)))};Function.prototype.partial=function(){return bind.apply(null,[this,null].concat(Array.prototype.slice.call(arguments)))};Function.prototype.inherits=function(parentCtor){var tempCtor=function(){};this.superClass_=tempCtor.prototype=parentCtor.prototype;this.prototype=new tempCtor};
Function.prototype.mixin=function(props){for(var x$20 in props)this.prototype[x$20]=props[x$20];if(typeof props.toString=="function"&&props.toString!=this.prototype.toString)this.prototype.toString=props.toString};var DB_mode=false;function DumpError(str$1){try{throw str$1;}catch(e){DumpException(e)}}function DumpException(e$1,opt_msg){var title="Javascript exception: "+(opt_msg?opt_msg:"")+" "+e$1;if(BR_IsIE())title+=" "+e$1.name+": "+e$1.message+" ("+e$1.number+")";var error="";if(typeof e$1=="string")error=e$1+"\n";else for(var i$6 in e$1)try{error+=i$6+": "+e$1[i$6]+"\n"}catch(ex){}error+=DB_GetStackTrace(DumpException.caller);DB_WriteDebugMsg(title+"\n"+error,1)}var function_name_re_=/function (\w+)/;
function DB_GetFunctionName(fn$4){var m=function_name_re_.exec(String(fn$4));if(m)return m[1];return""}
function DB_GetStackTrace(fn$5){try{if(!BR_IsIE()&&!(BR_AgentContains_("safari")||BR_AgentContains_("konqueror"))&&BR_AgentContains_("mozilla"))return Error().stack;if(!fn$5)return"";var x$21="- "+DB_GetFunctionName(fn$5)+"(",i$7=0;for(;i$7<fn$5.arguments.length;i$7++){if(i$7>0)x$21+=", ";var arg=String(fn$5.arguments[i$7]);if(arg.length>40)arg=arg.substr(0,40)+"...";x$21+=arg}x$21+=")\n";x$21+=DB_GetStackTrace(fn$5.caller);return x$21}catch(ex$1){return"[Cannot get stack trace]: "+ex$1+"\n"}}
var DB_starttime,DB_win=null,DB_winopening=false;
function DB_OpenDebugWindow(){if((DB_win==null||DB_win.closed)&&!DB_winopening)try{DB_winopening=true;DB_win=window.open("","debug","width=700,height=500,toolbar=no,resizable=yes,scrollbars=yes,left=16,top=16,screenx=16,screeny=16");DB_win.blur();DB_win.document.open();DB_winopening=false;var html$2="<font color=#ff0000><b>To turn off this debugging window,hit 'D' inside the main caribou window, then close this window.</b></font><br>";DB_WriteDebugHtml(html$2)}catch(ex$2){}}
function DB_WriteDebugMsg(str$3,level){if(DB_mode){try{var t=(new Date).getTime()-DB_starttime,html$3="["+t+"] "+HtmlEscape(str$3).replace(/\n/g,"<br>")+"<br>";if(level==1){html$3="<font color=#ff0000><b>Error: "+html$3+"</b></font>";DB_win.focus()}}catch(ex$3){}DB_WriteDebugHtml(html$3)}else typeof log!="undefined"&&log(HtmlEscape(str$3))}function DB_WriteDebugHtml(html$4){if(!!DB_mode)try{DB_OpenDebugWindow();DB_win.document.write(html$4);DB_win.scrollTo(0,1000000)}catch(ex$4){}};function BR_AgentContains_(str$4){if(str$4 in BR_AgentContains_cache_)return BR_AgentContains_cache_[str$4];return BR_AgentContains_cache_[str$4]=navigator.userAgent.toLowerCase().indexOf(str$4)!=-1}var BR_AgentContains_cache_={};function BR_IsIE(){return BR_AgentContains_("msie")&&!window.opera}var amp_re_=/&/g,lt_re_=/</g,gt_re_=/>/g;function HtmlEscape(str$6){if(!str$6)return"";return str$6.replace(amp_re_,"&amp;").replace(lt_re_,"&lt;").replace(gt_re_,"&gt;").replace(quote_re_,"&quot;")}
var quote_re_=/\"/g;function forid_1(id$14){return document.getElementById(id$14)}function forid_2(id$15){return document.all[id$15]}var forid=document.getElementById?forid_1:forid_2;
function log(msg$2){try{if(window.parent!=window&&window.parent.log){window.parent.log(window.name+"::"+msg$2);return}}catch(e$9){}var logPane=forid("log");if(logPane){var logText="<p class=logentry><span class=logdate>"+new Date+"</span><span class=logmsg>"+msg$2+"</span></p>";logPane.innerHTML=logText+logPane.innerHTML}else window.status=msg$2};function AS_Assert(){}AS_Assert.raise=function(msg$3){if(typeof Error!="undefined")throw new Error(msg$3||"Assertion Failed");else throw msg$3;};AS_Assert.fail=function(opt_msg$6){opt_msg$6=opt_msg$6||"Assertion failed";typeof DumpError=="undefined"||DumpError(opt_msg$6+"\n");AS_Assert.raise(opt_msg$6)};AS_Assert.isTrue=function(expression$2,opt_msg$7){if(!expression$2){if(opt_msg$7===undefined)opt_msg$7="Assertion failed";AS_Assert.fail(opt_msg$7)}};
AS_Assert.equals=function(val1$1,val2$1,opt_msg$8){if(val1$1!=val2$1){if(opt_msg$8===undefined)opt_msg$8="AS_Assert.equals failed: <"+val1$1+"> != <"+val2$1+">";AS_Assert.fail(opt_msg$8)}};
AS_Assert.typeOf=function(value$5,type$2,opt_msg$9){if(!(typeof value$5==type$2)){if(value$5||value$5=="")try{if(type$2==AS_Assert.TYPE_MAP[typeof value$5]||value$5 instanceof type$2)return}catch(e$10){}if(opt_msg$9===undefined){if(typeof type$2=="function"){var match$2=type$2.toString().match(/^\s*function\s+([^\s\{]+)/);if(match$2)type$2=match$2[1]}opt_msg$9="AS_Assert.typeOf failed: <"+value$5+"> not typeof "+type$2}AS_Assert.fail(opt_msg$9)}};AS_Assert.TYPE_MAP={string:String,number:Number,"boolean":Boolean};
AS_Assert.numArgs=function(num$1,opt_msg$10){var caller$1=AS_Assert.numArgs.caller;if(caller$1&&caller$1.arguments.length!=num$1){if(opt_msg$10===undefined)opt_msg$10=caller$1.name+" expected "+num$1+" arguments  but received "+caller$1.arguments.length;AS_Assert.fail(opt_msg$10)}};Function.prototype.bind=function(thisObj){if(typeof this!="function")throw new Error("Bind must be called as a method of a function object.");var self$3=this,staticArgs=Array.prototype.splice.call(arguments,1,arguments.length);return function(){var args$2=staticArgs.concat(),i$25=0;for(;i$25<arguments.length;i$25++)args$2.push(arguments[i$25]);return self$3.apply(thisObj,args$2)}};var listen,unlisten,unlistenByKey;
(function(){var listeners={},nextId=0;function getHashCode_(obj$4){if(obj$4.listen_hc_==null)obj$4.listen_hc_=++nextId;return obj$4.listen_hc_}function createKey_(node$3,event$1,listener,opt_useCapture){var nodeHc=getHashCode_(node$3),listenerHc=getHashCode_(listener);opt_useCapture=!!opt_useCapture;var key=nodeHc+"_"+event$1+"_"+listenerHc+"_"+opt_useCapture;return key}listen=function(node$4,event$2,listener$1,opt_useCapture$1){var key$1=createKey_(node$4,event$2,listener$1,opt_useCapture$1);if(key$1 in
listeners)return key$1;var proxy=handleEvent.bind(null,key$1);listeners[key$1]={listener:listener$1,proxy:proxy,event:event$2,node:node$4,useCapture:opt_useCapture$1};if(node$4.addEventListener)node$4.addEventListener(event$2,proxy,opt_useCapture$1);else if(node$4.attachEvent)node$4.attachEvent("on"+event$2,proxy);else throw new Error("Node {"+node$4+"} does not support event listeners.");return key$1};unlisten=function(node$5,event$3,listener$2,opt_useCapture$2){var key$2=createKey_(node$5,event$3,
listener$2,opt_useCapture$2);return unlistenByKey(key$2)};unlistenByKey=function(key$3){if(!(key$3 in listeners))return false;var listener$3=listeners[key$3],proxy$1=listener$3.proxy,event$4=listener$3.event,node$6=listener$3.node,useCapture=listener$3.useCapture;if(node$6.removeEventListener)node$6.removeEventListener(event$4,proxy$1,useCapture);else node$6.detachEvent&&node$6.detachEvent("on"+event$4,proxy$1);delete listeners[key$3];return true};function handleEvent(key$4){var args$3=Array.prototype.splice.call(arguments,
1,arguments.length);return listeners[key$4].listener.apply(null,args$3)}})();function Point(x$28,y$9,opt_coordinateFrame){this.x=x$28;this.y=y$9;this.coordinateFrame=opt_coordinateFrame||null}Point.prototype.toString=function(){return"[P "+this.x+","+this.y+"]"};Point.prototype.clone=function(){return new Point(this.x,this.y,this.coordinateFrame)};function Delta(dx$4,dy$4){this.dx=dx$4;this.dy=dy$4}Delta.prototype.toString=function(){return"[D "+this.dx+","+this.dy+"]"};
function Rect(x$29,y$10,w$2,h$1,opt_coordinateFrame$1){this.x=x$29;this.y=y$10;this.w=w$2;this.h=h$1;this.coordinateFrame=opt_coordinateFrame$1||null}Rect.prototype.contains=function(p$4){return this.x<=p$4.x&&p$4.x<this.x+this.w&&this.y<=p$4.y&&p$4.y<this.y+this.h};
Rect.prototype.intersects=function(r){var p$5=function(x$30,y$11){return new Point(x$30,y$11,null)};return this.contains(p$5(r.x,r.y))||this.contains(p$5(r.x+r.w,r.y))||this.contains(p$5(r.x+r.w,r.y+r.h))||this.contains(p$5(r.x,r.y+r.h))||r.contains(p$5(this.x,this.y))||r.contains(p$5(this.x+this.w,this.y))||r.contains(p$5(this.x+this.w,this.y+this.h))||r.contains(p$5(this.x,this.y+this.h))};Rect.prototype.toString=function(){return"[R "+this.w+"x"+this.h+"+"+this.x+"+"+this.y+"]"};
Rect.prototype.clone=function(){return new Rect(this.x,this.y,this.w,this.h,this.coordinateFrame)};var XH_ieProgId_;
function XH_XmlHttpInit_(){var XH_ACTIVE_X_IDENTS=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];if(typeof XMLHttpRequest=="undefined"&&typeof ActiveXObject!="undefined"){var i$26=0;for(;i$26<XH_ACTIVE_X_IDENTS.length;i$26++){var candidate=XH_ACTIVE_X_IDENTS[i$26];try{new ActiveXObject(candidate);XH_ieProgId_=candidate;break}catch(e$12){}}if(!XH_ieProgId_)throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed.");}}
XH_XmlHttpInit_();function XH_XmlHttpPOST(xmlHttp$1,url$7,data$2,handler$1){xmlHttp$1.open("POST",url$7,true);xmlHttp$1.onreadystatechange=handler$1;xmlHttp$1.setRequestHeader("Content-Type","application/x-www-form-urlencoded");xmlHttp$1.setRequestHeader("Content-Length",data$2.length);XH_XmlHttpSend(xmlHttp$1,data$2)}function XH_XmlHttpSend(xmlHttp$4,data$3){try{xmlHttp$4.send(data$3)}catch(e$13){log("XMLHttpSend failed "+e$13.toString()+"<br>"+e$13.stack);throw e$13;}};if("undefined"==typeof log)log=function(){};function Dom(opt_doc){this.doc=opt_doc||document;this.getElementById_=this.doc.getElementById?function(id$16){return this.doc.getElementById(id$16)}:function(id$17){return this.doc.all[id$17]}}Dom.prototype.$=function(id$18){return this.getElementById_(id$18)};Dom.prototype.create=function(nodeName){return this.doc.createElement(nodeName)};Dom.prototype.createText=function(text$2){return this.doc.createTextNode(text$2)};Dom.remove=function(node$7){AS_Assert.isTrue(node$7.parentNode);node$7.parentNode.removeChild(node$7)};
Dom.insertAfter=function(newNode$3,refNode){AS_Assert.isTrue(refNode.parentNode);refNode.parentNode.insertBefore(newNode$3,refNode.nextSibling)};Dom.insertBefore=function(newNode$4,refNode$1){AS_Assert.isTrue(refNode$1.parentNode);refNode$1.parentNode.insertBefore(newNode$4,refNode$1)};Dom.replace=function(newNode$5,oldNode){AS_Assert.isTrue(oldNode.parentNode);oldNode.parentNode.replaceChild(newNode$5,oldNode)};
Dom.getInnerText=function(node$8){var innerText=[];Dom.getInnerTextHelp_(node$8,innerText);return innerText.join("")};Dom.getInnerTextHelp_=function(node$9,stringBuffer){if(node$9.innerText)stringBuffer.push(node$9.innerText);else if(node$9.data)stringBuffer.push(node$9.data);else if(node$9.hasChildNodes()){var child$3=node$9.firstChild;for(;child$3;){arguments.callee(child$3,stringBuffer);child$3=child$3.nextSibling}}};new Dom;if(window.jstiming){window.jstiming.beaconImageReferences_={};window.jstiming.nextImageId_=1;function getTick(timer,label,opt_start){var start$4,tick=timer.t[label];if(!tick)return undefined;var start$4=opt_start!=undefined?opt_start:timer.t.start;return tick-start$4}window.jstiming.report=function(timer$4,opt_extraParams,opt_reportUri){var extra="";if(window.jstiming.pt){extra+="&srt="+window.jstiming.pt;delete window.jstiming.pt}try{if(window.external.tran)extra+="&tran="+window.external.tran}catch(e$16){}var ticks=
timer$4.t,start$5=ticks.start,rt=[];for(var label$3 in ticks)label$3=="start"||start$5&&rt.push(label$3+"."+getTick(timer$4,label$3));delete ticks.start;if(opt_extraParams)for(var arg$1 in opt_extraParams)extra+="&"+arg$1+"="+opt_extraParams[arg$1];var img=new Image,id$20=window.jstiming.nextImageId_++;window.jstiming.beaconImageReferences_[id$20]=img;img.onload=img.onerror=function(){delete window.jstiming.beaconImageReferences_[id$20]};img.src=[opt_reportUri?opt_reportUri:"http://csi.gstatic.com/csi",
"?v=3","&s="+(window.jstiming.sn?window.jstiming.sn:"codesite")+"&action=",timer$4.name,extra,"&rt=",rt.join(",")].join("");img=null}};var CS_star={};
function CS_toggleStar(el$19,args$4,star_msg_id,star_on_msg,star_off_msg){var starred=el$19.src.indexOf("star_off.gif")!=-1?1:0;el$19.src=starred?"http://www.gstatic.com/codesite/ph/images/star_on.gif":"http://www.gstatic.com/codesite/ph/images/star_off.gif";var star_msg_el=document.getElementById(star_msg_id);if(star_msg_el)star_msg_el.innerHTML=starred?star_on_msg:star_off_msg;CS_star={on_msg:star_on_msg,off_msg:star_off_msg,img_el:el$19,msg_el:star_msg_el};args$4.starred=starred;CS_setStar(args$4)}
var CS_starXmlHttp=undefined;function CS_setStar(args$5){CS_starXmlHttp=XH_ieProgId_?new ActiveXObject(XH_ieProgId_):new XMLHttpRequest;var setStarURL="/hosting/stars.do",data$4="";for(var i$30 in args$5)data$4+=i$30+"="+encodeURIComponent(args$5[i$30])+"&";XH_XmlHttpPOST(CS_starXmlHttp,setStarURL,data$4,CS_setStarCallback)}function CS_setStarCallback(){CS_starXmlHttp.readyState==4&&CS_starXmlHttp.status==200&&CS_gotSetStar(CS_starXmlHttp.responseText)}
function CS_gotSetStar(responseText){try{var args$6=eval("_d="+responseText),starred$1=args$6.starred;CS_star.img_el.src=starred$1?"http://www.gstatic.com/codesite/ph/images/star_on.gif":"http://www.gstatic.com/codesite/ph/images/star_off.gif";if(CS_star.msg_el)CS_star.msg_el.innerHTML=starred$1?CS_star.on_msg:CS_star.off_msg}catch(e$18){return null}};_CS_toggleStar=CS_toggleStar;(function(){function getPageType(url$10){var URL_FILTER=/http:\/\/[^\/]*\/(u|hosting|p)\/([^\?\/]*)\/?([^\?\/]*)\/?([^\?\/]*)?/,urlArray=URL_FILTER.exec(url$10);if(urlArray[1]=="hosting"){if(urlArray[2])return"hosting_"+urlArray[2];return"hosting_home"}if(urlArray[1]=="u"){if(urlArray[3]=="updates"){if(urlArray[4])return"user_updates_"+urlArray[4];return"user_updates_user"}return"user_profile"}if(urlArray[1]=="p"){if(!urlArray[3]&&!urlArray[4])return"summary";if(urlArray[3]=="wiki")return urlArray[3];
if(urlArray[3]&&!urlArray[4])return urlArray[3];if(urlArray[3]&&urlArray[4]){var page=urlArray[3]=="w"?"wiki":urlArray[3];return page+"_"+urlArray[4]}}return"other"}function getActionNames(){var names=["codesite","ph"],pageType="project_"+getPageType(window.location.href);names.push(pageType);return names.join(",")}function onLoadCsi(){var loadTimer=window.jstiming.load;loadTimer.tick("plt");loadTimer.name=getActionNames();window.setTimeout(function(){window.jstiming.report(loadTimer)},500)}function reportToCsi(){if(window.attachEvent)window.attachEvent("onload",
onLoadCsi);else window.addEventListener&&window.addEventListener("load",onLoadCsi,false)}window._CS_reportToCsi=reportToCsi})();(function(){function loadAnalytics(){window.setTimeout(function(){var gaJsHost="https:"==document.location.protocol?"https://ssl.":"http://www.",url$11=gaJsHost+"google-analytics.com/ga.js",script=document.createElement("script");script.src=url$11;script.type="text/javascript";document.getElementsByTagName("head")[0].appendChild(script);_CS_reportAnalytics()},0)}if(window.attachEvent)window.attachEvent("onload",loadAnalytics);else window.addEventListener&&window.addEventListener("load",loadAnalytics,
false)})();(function(){var export_name="Menu";window[export_name]=function(target,opt_trigger,opt_triggerType){this.iid=window[export_name].instance.length;window[export_name].instance[this.iid]=this;this.target=typeof target=="string"?document.getElementById(target):target;this.trigger=(opt_trigger=typeof opt_trigger=="string"?document.getElementById(opt_trigger):opt_trigger)||target;this.items=[];this.onOpenEvents=[];this.triggerType=opt_triggerType||"click";this.menu=this.createElement("div","menuDiv instance"+
this.iid);this.icon=this.createIcon();this.hide();this.addCategory("default");this.addEvent(this.trigger,this.triggerType,this.wrap(this.toggle));this.addEvent(window,"resize",this.wrap(this.adjustSizeAndLocation));this.addEvent(document,"click",this.wrap(this.hide));this.addEvent(this.menu,"click",this.stopPropagation());this.addEvent(this.trigger,"click",this.stopPropagation());this.addEvent(this.icon,"click",this.stopPropagation())};window[export_name].prototype={target:null,trigger:null,triggerType:null,
menu:null,icon:null,categories:null,thread:-1,iid:-1,items:null,scrolls:false,onOpenEvents:null,createElement:function(element$3,opt_className,opt_content){var div$3=document.createElement(element$3);div$3.className=opt_className;opt_content&&this.append(opt_content,div$3);return div$3},createIcon:function(){var icon=this.createElement("img","menuIcon off instance"+this.iid);icon.setAttribute("src","http://www.gstatic.com/codesite/ph/images/cleardot.gif");icon.setAttribute("height","14");icon.setAttribute("width",
"14");icon.style.verticalAlignment="middle";this.target.parentNode.insertBefore(icon,this.target.nextSibling);this.addEvent(this.trigger,"mouseover",this.wrap(this.iconOver,icon));this.addEvent(this.trigger,"mouseout",this.wrap(this.iconOut,icon));this.addEvent(icon,"mouseover",this.wrap(this.iconOver,icon));this.addEvent(icon,"mouseout",this.wrap(this.iconOut,icon));this.addEvent(icon,"mousedown",this.wrap(this.toggle));return icon},iconOver:function(){if(this.className)this.className=this.className.replace(/ off/g,
" on")},iconOut:function(opt_down){if(this.className){var regex=opt_down?/ (on|down)/g:/ on/g;this.className=this.className.replace(regex," off")}},iconDown:function(){if(this.className)this.className=this.className.replace(/ (off|on)/g," down")},addEvent:function(element$4,eventType,callback$3){if(element$4.addEventListener)element$4.addEventListener(eventType,callback$3,false);else try{element$4.attachEvent("on"+eventType,callback$3)}catch(e$19){element$4["on"+eventType]=callback$3}},addOnOpen:function(eventCallback){var eventIndex=
this.onOpenEvents.length;this.onOpenEvents.push(eventCallback);return eventIndex},wrap:function(callback$4,opt_thisObj){var closured_callback=callback$4,this_object=opt_thisObj||this;return function(){closured_callback.apply(this_object)}},addCategory:function(category,opt_title){this.categories=this.categories||[];var categoryDiv=this.createElement("div","menuCategory "+category);categoryDiv._categoryName=category;if(opt_title){var categoryTitle=this.createElement("b","categoryTitle "+category,opt_title);
categoryTitle.style.display="block";this.append(categoryTitle)}this.append(categoryDiv);return this.categories[this.categories.length]=this.categories[category]=categoryDiv},emptyCategory:function(category$1){if(!!this.categories[category$1]){var div$4=this.categories[category$1],i$31=div$4.childNodes.length-1;for(;i$31>=0;i$31--)div$4.removeChild(div$4.childNodes[i$31])}},clear:function(){var i$32=0;for(;i$32<this.categories.length;i$32++)this.categories[this.categories[i$32]._categoryName]=null;
this.items.splice(0,this.items.length);this.categories.splice(0,this.categories.length);this.categories=[];this.items=[];this.menu.innerHTML=""},removeItem:function(item){var result$4=null,i$33=0;for(;i$33<this.items.length;i$33++){if(this.items[i$33]==item){result$4=this.items[i$33];this.items.splice(i$33,1)}this.items[i$33].item._index=i$33}return result$4},removeCategory:function(category$2){var div$5=this.categories[category$2];if(!(!div$5||!div$5.parentNode)){div$5.parentNode.removeChild(div$5);
var i$34=0;for(;i$34<this.categories.length;i$34++)if(this.categories[i$34]===div$5){this.categories[this.categories[i$34]._categoryName]=null;this.categories.splice(i$34,1);return}var i$34=0;for(;i$34<div$5.childNodes.length;i$34++)div$5.childNodes[i$34]._index?this.items.splice(div$5.childNodes[i$34]._index,1):this.removeItem(div$5.childNodes[i$34])}},addItem:function(html_or_element,opt_href,opt_category,opt_title$1){var category$3=opt_category?this.categories[opt_category]||this.addCategory(opt_category,
opt_title$1):this.categories["default"],menuItem=this.createElement("a","menuItem",html_or_element),menuHref=opt_href||"#",itemText=typeof html_or_element=="string"?html_or_element:html_or_element.innerText||"ERROR";menuItem.style.display="block";menuItem.setAttribute("href",menuHref);menuItem._index=this.items.length;this.append(menuItem,category$3);this.items[this.items.length]={item:menuItem,text:itemText};return menuItem},addSeparator:function(opt_category$1,opt_title$2){var category$4=opt_category$1?
this.categories[opt_category$1]||this.addCategory(opt_category$1,opt_title$2):this.categories["default"],hr=this.createElement("hr","menuSeparator");this.append(hr,category$4)},adjustSizeAndLocation:function(){var style$1=this.menu.style;style$1.position="absolute";var firstCategory=null,i$35=0;for(;i$35<this.categories.length;i$35++){this.categories[i$35].className=this.categories[i$35].className.replace(/ first/,"");if(this.categories[i$35].childNodes.length==0)this.categories[i$35].style.display=
"none";else{this.categories[i$35].style.display="";if(!firstCategory){firstCategory=this.categories[i$35];firstCategory.className+=" first"}}}var alreadyVisible=style$1.display!="none"&&style$1.visibility!="hidden",docElemWidth=document.documentElement.clientWidth,docElemHeight=document.documentElement.clientHeight,pageSize={w:(window.innerWidth||docElemWidth&&docElemWidth>0?docElemWidth:document.body.clientWidth)||1,h:(window.innerHeight||docElemHeight&&docElemHeight>0?docElemHeight:document.body.clientHeight)||
1},iconPos=this.find(this.icon),iconSize={w:this.icon.offsetWidth,h:this.icon.offsetHeight},targetPos=this.find(this.target),targetSize={w:this.target.offsetWidth,h:this.target.offsetHeight},menuSize={w:this.menu.offsetWidth,h:this.menu.offsetHeight};if(!alreadyVisible){var oldVisibility=style$1.visibility,oldDisplay=style$1.display;style$1.visibility="hidden";style$1.display="";style$1.height="";style$1.width="";menuSize={w:this.menu.offsetWidth,h:this.menu.offsetHeight};style$1.display=oldDisplay;
style$1.visibility=oldVisibility}var addScroll=this.menu.offsetHeight/pageSize.h>0.8;if(addScroll){menuSize.h=parseInt(pageSize.h*0.8,10);style$1.height=menuSize.h+"px";style$1.overflowX="hidden";style$1.overflowY="auto"}else style$1.height=style$1.overflowY=style$1.overflowX="";style$1.top=targetPos.y+targetSize.h+"px";style$1.left=targetPos.x+"px";if(menuSize.w<175)style$1.width="175px";if(addScroll)style$1.width=parseInt(style$1.width,10)+13+"px";if(targetPos.x+menuSize.w>pageSize.w)style$1.left=
iconPos.x-(menuSize.w-iconSize.w)+"px"},html:function(opt_html){var result$5=this.menu.innerHTML;if(opt_html)this.menu.innerHTML=opt_html;return result$5},append:function(html_or_element$1,opt_target){var element$5=opt_target||this.menu;if(typeof opt_target=="string"&&this.categories[opt_target])element$5=this.categories[opt_target];if(typeof html_or_element$1=="string")element$5.innerHTML+=html_or_element$1;else element$5.appendChild(html_or_element$1)},over:function(){this.menu.style.display!="none"&&
this.show();if(this.thread!=-1){clearTimeout(this.thread);this.thread=-1}},out:function(){if(this.thread!=-1){clearTimeout(this.thread);this.thread=-1}this.thread=setTimeout(this.wrap(this.hide),400)},stopPropagation:function(){return function(e$20){if(!e$20)var e$20=window.event;e$20.cancelBubble=true;e$20.stopPropagation&&e$20.stopPropagation()}},toggle:function(){this.menu.style.display=="none"?this.show():this.hide()},show:function(){if(this.menu.style.display!=""){var i$36=0;for(;i$36<this.onOpenEvents.length;i$36++)this.onOpenEvents[i$36].call(null,
this);this.menu.style.visibility="hidden";this.menu.style.display="";this.adjustSizeAndLocation();this.iconDown.apply(this.icon);this.trigger.nodeName&&this.trigger.nodeName=="A"&&this.trigger.blur();this.menu.style.visibility="visible"}},hide:function(){this.iconOut.apply(this.icon,[true]);this.menu.style.display="none"},find:function(element$6){var curleft=0,curtop=0;if(element$6.offsetParent){do{curleft+=element$6.offsetLeft;curtop+=element$6.offsetTop}while((element$6=element$6.offsetParent)&&
element$6.style&&element$6.style.position!="relative"&&element$6.style.position!="absolute")}return{x:curleft,y:curtop}}};window[export_name].instance=[]})();(function(){var target$1=document.getElementById("projects-dropdown");if(target$1){window.myprojects=new Menu(target$1);window._addProjects=function(jsonData){myprojects.clear();var starred$2=[],projects$1=[];for(var category$5 in jsonData)switch(category$5){case "memberof":case "ownerof":var i$37=0;for(;i$37<jsonData[category$5].length;i$37++)projects$1.push(jsonData[category$5][i$37]);break;case "starred":var i$37=0;for(;i$37<jsonData[category$5].length;i$37++)starred$2.push(jsonData[category$5][i$37]);
break;default:break}projects$1.sort();var i$37=0;for(;i$37<projects$1.length;i$37++)myprojects.addItem(projects$1[i$37],"/p/"+projects$1[i$37]+"/","projects","Projects");starred$2.sort();var i$37=0;for(;i$37<starred$2.length;i$37++)myprojects.addItem(starred$2[i$37],"/p/"+starred$2[i$37]+"/","starred","Starred");myprojects.addSeparator("controls","");myprojects.addItem("Find or start a project...","/hosting/","controls");var scriptTag=document.getElementById("_myprojects_script");scriptTag.parentNode.removeChild(scriptTag)};
var loadItems=function(){var script$1=document.getElementById("_myprojects_script");if(!script$1){var elem$1=document.createElement("script");elem$1.src="/hosting/projects?jsonp=_addProjects";elem$1.setAttribute("id","_myprojects_script");document.getElementsByTagName("head")[0].appendChild(elem$1)}};myprojects.addEvent(window,"load",loadItems);myprojects.addOnOpen(loadItems);if(window.addEventListener)window.addEventListener("load",function(){document.body.appendChild(myprojects.menu)},false);else window.attachEvent&&
window.attachEvent("onload",function(){document.body.appendChild(myprojects.menu)})}})();
})()
