/* Copyright 2006 Google Inc. All Rights Reserved. */ (function(){
var global=this;String.prototype.startsWith=function(a){return this.indexOf(a)==0};String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};if(!Function.prototype.apply)Function.prototype.apply=function(a,b){var c=[],d,e;a||(a=global);var f=b||[],g=0;for(;g<f.length;g++)c[g]="args["+g+"]";e="oScope.__applyTemp__.peek()("+c.join(",")+");";if(!a.__applyTemp__)a.__applyTemp__=[];a.__applyTemp__.push(this);d=eval(e);a.__applyTemp__.pop();return d};
if(!Array.prototype.push)Array.prototype.push=function(){var a=0;for(;a<arguments.length;a++)this[this.length]=arguments[a];return this.length};if(!Array.prototype.pop)Array.prototype.pop=function(){if(!!this.length){var a=this[this.length-1];this.length--;return a}};Array.prototype.peek=function(){return this[this.length-1]};if(!Array.prototype.shift)Array.prototype.shift=function(){if(!(this.length==0)){var a=this[0],b=0;for(;b<this.length-1;b++)this[b]=this[b+1];this.length--;return a}};
if(!Array.prototype.unshift)Array.prototype.unshift=function(){var a=arguments.length,b=this.length-1;for(;b>=0;b--)this[b+a]=this[b];var c=0;for(;c<a;c++)this[c]=arguments[c];return this.length};if(!Array.prototype.forEach)Array.prototype.forEach=function(a,b){var c=0;for(;c<this.length;c++)a.call(b,this[c],c,this)};
function bind(a,b){var c=a.boundArgs_||[];c=c.concat(Array.prototype.slice.call(arguments,2));if(typeof a.boundSelf_!="undefined")b=a.boundSelf_;if(typeof a.boundFn_!="undefined")a=a.boundFn_;var d=function(){var e=c.concat(Array.prototype.slice.call(arguments));return a.apply(b,e)};d.boundArgs_=c;d.boundSelf_=b;d.boundFn_=a;return d}Function.prototype.bind=function(a){return bind.apply(null,[this,a].concat(Array.prototype.slice.call(arguments,1)))};var DB_mode=false;function Debug(a){DB_WriteDebugMsg(a,0)}function DumpError(a){try{throw a;}catch(b){DumpException(b)}}function DumpException(a,b){var c="Javascript exception: "+(b?b:"")+" "+a;if(BR_IsIE())c+=" "+a.name+": "+a.message+" ("+a.number+")";var d="";if(typeof a=="string")d=a+"\n";else for(var e in a)try{d+=e+": "+a[e]+"\n"}catch(f){}d+=DB_GetStackTrace(DumpException.caller);DB_WriteDebugMsg(c+"\n"+d,1)}var function_name_re_=/function (\w+)/;
function DB_GetFunctionName(a){var b=function_name_re_.exec(String(a));if(b)return b[1];return""}function DB_GetStackTrace(a){try{if(BR_IsNav())return Error().stack;if(!a)return"";var b="- "+DB_GetFunctionName(a)+"(",c=0;for(;c<a.arguments.length;c++){if(c>0)b+=", ";var d=String(a.arguments[c]);if(d.length>40)d=d.substr(0,40)+"...";b+=d}b+=")\n";b+=DB_GetStackTrace(a.caller);return b}catch(e){return"[Cannot get stack trace]: "+e+"\n"}}var DB_starttime,DB_win=null,DB_winopening=false;
function DB_OpenDebugWindow(){if((DB_win==null||DB_win.closed)&&!DB_winopening)try{DB_winopening=true;DB_win=window.open("","debug","width=700,height=500,toolbar=no,resizable=yes,scrollbars=yes,left=16,top=16,screenx=16,screeny=16");DB_win.blur();DB_win.document.open();DB_winopening=false;var a="<font color=#ff0000><b>To turn off this debugging window,hit 'D' inside the main caribou window, then close this window.</b></font><br>";DB_WriteDebugHtml(a)}catch(b){}}
function DB_WriteDebugMsg(a,b){if(DB_mode){try{var c=(new Date).getTime()-DB_starttime,d="["+c+"] "+HtmlEscape(a).replace(/\n/g,"<br>")+"<br>";if(b==1){d="<font color=#ff0000><b>Error: "+d+"</b></font>";DB_win.focus()}}catch(e){}DB_WriteDebugHtml(d)}else typeof log!="undefined"&&log(HtmlEscape(a))}function DB_WriteDebugHtml(a){if(!!DB_mode)try{DB_OpenDebugWindow();DB_win.document.write(a);DB_win.scrollTo(0,1000000)}catch(b){}};function BR_AgentContains_(a){if(a in BR_AgentContains_cache_)return BR_AgentContains_cache_[a];return BR_AgentContains_cache_[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var BR_AgentContains_cache_={};function BR_IsIE(){return BR_AgentContains_("msie")&&!window.opera}function BR_IsSafari(){return BR_AgentContains_("safari")||BR_AgentContains_("konqueror")}function BR_IsNav(){return!BR_IsIE()&&!BR_IsSafari()&&BR_AgentContains_("mozilla")}
function raise(a){if(typeof Error!="undefined")throw new Error(a||"Assertion Failed");else throw a;}function Fail(a){a=a||"Assertion failed";IsDefined(DumpError)&&DumpError(a+"\n");raise(a)}function AssertType(a,b,c){if(!(typeof a==b)){if(a||a=="")try{if(b==AssertTypeMap[typeof a]||a instanceof b)return}catch(d){}var e=c===undefined;if(e){if(typeof b=="function"){var f=b.toString().match(/^\s*function\s+([^\s\{]+)/);if(f)b=f[1]}c="AssertType failed: <"+a+"> not typeof "+b}Fail(c)}}
var AssertTypeMap={string:String,number:Number,"boolean":Boolean};function ShowElement(a,b){a.style.display=b?"":"none"}function HasClass(a,b){if(a==null||a.className==null)return false;if(a.className==b)return true;var c=a.className.split(" "),d=0;for(;d<c.length;d++)if(c[d]==b)return true;return false}function AddClass(a,b){HasClass(a,b)||(a.className+=" "+b)}
function RemoveClass(a,b){if(!(a.className==null))if(a.className==b)a.className="";else{var c=a.className.split(" "),d=[],e=false,f=0;for(;f<c.length;f++)if(c[f]!=b)c[f]&&d.push(c[f]);else e=true;if(e)a.className=d.join(" ")}}var getScrollTopGetters_={ieQuirks_:function(a){return a.document.body.scrollTop},ieStandards_:function(a){return a.document.documentElement.scrollTop},dom_:function(a){return a.pageYOffset}};
var getScrollLeftGetters_={ieQuirks_:function(a){return a.document.body.scrollLeft},ieStandards_:function(a){return a.document.documentElement.scrollLeft},dom_:function(a){return a.pageXOffset}};function GetWindowPropertyByBrowser_(a,b){try{if(BR_IsSafari())return b.dom_(a);else if(!window.opera&&"compatMode"in a.document&&a.document.compatMode=="CSS1Compat")return b.ieStandards_(a);else if(BR_IsIE())return b.ieQuirks_(a)}catch(c){}return b.dom_(a)}var amp_re_=/&/g,lt_re_=/</g,gt_re_=/>/g;
function HtmlEscape(a){if(!a)return"";return a.replace(amp_re_,"&amp;").replace(lt_re_,"&lt;").replace(gt_re_,"&gt;").replace(quote_re_,"&quot;")}var quote_re_=/\"/g;
function GetCursorPos(a,b){try{if(IsDefined(b.selectionEnd))return b.selectionEnd;else if(a.document.selection&&a.document.selection.createRange){var c=a.document.selection.createRange();if(c.parentElement()!=b)return-1;var d=c.duplicate();d.moveToElementText(b);d.setEndPoint("EndToStart",c);var e=d.text.length;if(e>b.value.length)return-1;return e}else{Debug("Unable to get cursor position for: "+navigator.userAgent);return b.value.length}}catch(f){DumpException(f,"Cannot get cursor pos")}return-1}
function SetCursorPos(a,b,c){if(IsDefined(b.selectionEnd)&&IsDefined(b.selectionStart)){b.selectionStart=c;b.selectionEnd=c}else if(a.document.selection&&b.createTextRange){var d=b.createTextRange();d.collapse(true);d.move("character",c);d.select()}}function FindInArray(a,b){var c=0;for(;c<a.length;c++)if(a[c]==b)return c;return-1}function DeleteArrayElement(a,b){var c=0;for(;c<a.length&&a[c]!=b;)c++;a.splice(c,1)}function IsDefined(a){return typeof a!="undefined"}
function GetKeyCode(a){var b;if(a.keyCode)b=a.keyCode;else if(a.which)b=a.which;return b}function forid_1(a){return document.getElementById(a)}function forid_2(a){return document.all[a]}var forid=document.getElementById?forid_1:forid_2;
function log(a){try{if(window.parent!=window&&window.parent.log){window.parent.log(window.name+"::"+a);return}}catch(b){}var c=forid("log");if(c){var d="<p class=logentry><span class=logdate>"+new Date+"</span><span class=logmsg>"+a+"</span></p>";c.innerHTML=d+c.innerHTML}else window.status=a};function AS_Assert(){}AS_Assert.raise=function(a){if(typeof Error!="undefined")throw new Error(a||"Assertion Failed");else throw a;};AS_Assert.fail=function(a){a=a||"Assertion failed";typeof DumpError=="undefined"||DumpError(a+"\n");AS_Assert.raise(a)};AS_Assert.isTrue=function(a,b){if(!a){if(b===undefined)b="Assertion failed";AS_Assert.fail(b)}};AS_Assert.equals=function(a,b,c){if(a!=b){if(c===undefined)c="AS_Assert.equals failed: <"+a+"> != <"+b+">";AS_Assert.fail(c)}};
AS_Assert.typeOf=function(a,b,c){if(!(typeof a==b)){if(a||a=="")try{if(b==AS_Assert.TYPE_MAP[typeof a]||a instanceof b)return}catch(d){}if(c===undefined){if(typeof b=="function"){var e=b.toString().match(/^\s*function\s+([^\s\{]+)/);if(e)b=e[1]}c="AS_Assert.typeOf failed: <"+a+"> not typeof "+b}AS_Assert.fail(c)}};AS_Assert.TYPE_MAP={string:String,number:Number,"boolean":Boolean};
AS_Assert.numArgs=function(a,b){var c=AS_Assert.numArgs.caller;if(c&&c.arguments.length!=a){if(b===undefined)b=c.name+" expected "+a+" arguments  but received "+c.arguments.length;AS_Assert.fail(b)}};Function.prototype.bind=function(a){if(typeof this!="function")throw new Error("Bind must be called as a method of a function object.");var b=this,c=Array.prototype.splice.call(arguments,1,arguments.length);return function(){var d=c.concat(),e=0;for(;e<arguments.length;e++)d.push(arguments[e]);return b.apply(a,d)}};var listen,unlisten,unlistenByKey;
(function(){var a={},b=0;function c(f){if(f.listen_hc_==null)f.listen_hc_=++b;return f.listen_hc_}function d(f,g,h,i){var j=c(f),k=c(h);i=!!i;var l=j+"_"+g+"_"+k+"_"+i;return l}listen=function(f,g,h,i){var j=d(f,g,h,i);if(j in a)return j;var k=e.bind(null,j);a[j]={listener:h,proxy:k,event:g,node:f,useCapture:i};if(f.addEventListener)f.addEventListener(g,k,i);else if(f.attachEvent)f.attachEvent("on"+g,k);else throw new Error("Node {"+f+"} does not support event listeners.");return j};unlisten=function(f,
g,h,i){var j=d(f,g,h,i);return unlistenByKey(j)};unlistenByKey=function(f){if(!(f in a))return false;var g=a[f],h=g.proxy,i=g.event,j=g.node,k=g.useCapture;if(j.removeEventListener)j.removeEventListener(i,h,k);else j.detachEvent&&j.detachEvent("on"+i,h);delete a[f];return true};function e(f){var g=Array.prototype.splice.call(arguments,1,arguments.length);return a[f].listener.apply(null,g)}})();function Point(a,b,c){this.x=a;this.y=b;this.coordinateFrame=c||null}Point.prototype.toString=function(){return"[P "+this.x+","+this.y+"]"};function Delta(a,b){this.dx=a;this.dy=b}Delta.prototype.toString=function(){return"[D "+this.dx+","+this.dy+"]"};function Rect(a,b,c,d,e){this.x=a;this.y=b;this.w=c;this.h=d;this.coordinateFrame=e||null}Rect.prototype.contains=function(a){return this.x<=a.x&&a.x<this.x+this.w&&this.y<=a.y&&a.y<this.y+this.h};
Rect.prototype.toString=function(){return"[R "+this.w+"x"+this.h+"+"+this.x+"+"+this.y+"]"};function nodeBounds(a){if(!a)return null;function b(j){var k=a.offsetParent;for(;k&&k.offsetParent;k=k.offsetParent){if(k.scrollLeft)j.x-=k.scrollLeft;if(k.scrollTop)j.y-=k.scrollTop}}var c;c=a.ownerDocument&&a.ownerDocument.parentWindow?a.ownerDocument.parentWindow:window;if(a.ownerDocument&&a.ownerDocument.getBoxObjectFor){var d=a.ownerDocument.getBoxObjectFor(a),e=new Rect(d.x,d.y,d.width,d.height,c);b(e);return e}if(a.getBoundingClientRect){var f=a.getBoundingClientRect();return new Rect(f.left+
GetWindowPropertyByBrowser_(c,getScrollLeftGetters_),f.top+GetWindowPropertyByBrowser_(c,getScrollTopGetters_),f.right-f.left,f.bottom-f.top,c)}var g=0,h=0,i=a;for(;i.offsetParent;i=i.offsetParent){g+=i.offsetLeft;h+=i.offsetTop}var e=new Rect(g,h,a.offsetWidth,a.offsetHeight,c);b(e);return e}
function GetMousePosition(a){var b=0,c=0;if(a.pageX||a.pageY){b=a.pageX;c=a.pageY}else if(a.clientX||a.clientY){var d=a.target?a.target:a.srcElement,e;e=d.ownerDocument&&d.ownerDocument.parentWindow?d.ownerDocument.parentWindow:window;b=a.clientX+GetWindowPropertyByBrowser_(e,getScrollLeftGetters_);c=a.clientY+GetWindowPropertyByBrowser_(e,getScrollTopGetters_)}return new Point(b,c,window)};var XH_ieProgId_;function XH_XmlHttpInit_(){var a=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];if(typeof XMLHttpRequest=="undefined"&&typeof ActiveXObject!="undefined"){var b=0;for(;b<a.length;b++){var c=a[b];try{new ActiveXObject(c);XH_ieProgId_=c;break}catch(d){}}if(!XH_ieProgId_)throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed.");}}XH_XmlHttpInit_();
function XH_XmlHttpCreate(){return XH_ieProgId_?new ActiveXObject(XH_ieProgId_):new XMLHttpRequest}function XH_XmlHttpGET(a,b,c){a.open("GET",b,true);a.onreadystatechange=c;XH_XmlHttpSend(a,null)}function XH_XmlHttpSend(a,b){try{a.send(b)}catch(c){log("XMLHttpSend failed "+c.toString()+"<br>"+c.stack);throw c;}};if("undefined"==typeof log)log=function(){};function Dom(a){this.doc=a||document;this.getElementById_=this.doc.getElementById?function(b){return this.doc.getElementById(b)}:function(b){return this.doc.all[b]}}Dom.prototype.$=function(a){return this.getElementById_(a)};Dom.remove=function(a){AS_Assert.isTrue(a.parentNode);a.parentNode.removeChild(a)};Dom.insertAfter=function(a,b){AS_Assert.isTrue(b.parentNode);b.parentNode.insertBefore(a,b.nextSibling)};
Dom.insertBefore=function(a,b){AS_Assert.isTrue(b.parentNode);b.parentNode.insertBefore(a,b)};Dom.replace=function(a,b){AS_Assert.isTrue(b.parentNode);b.parentNode.replaceChild(a,b)};Dom.getInnerText=function(a){var b=[];Dom.getInnerTextHelp_(a,b);return b.join("")};Dom.getInnerTextHelp_=function(a,b){if(a.innerText)b.push(a.innerText);else if(a.data)b.push(a.data);else if(a.hasChildNodes()){var c=a.firstChild;for(;c;){arguments.callee(c,b);c=c.nextSibling}}};var DM_GlobalDom=new Dom;
function $(a){return DM_GlobalDom.$(a)};function PopupController(){this.activePopups_=[]}function _PC_Install(a){if(gPopupControllerInstalled)return false;gPopupControllerInstalled=true;var b=a?a:document;listen(b.body,"mousedown",PC_notifyPopups);return true}
function PC_notifyPopups(a){if(gPopupController.activePopups_.length==0)return false;a=a||window.event;var b=gPopupController.activePopups_.length-1;for(;b>=0;--b){var c=gPopupController.activePopups_[b];PC_assertIsPopup(c);c.deactivate(a)&&gPopupController.activePopups_.splice(b,1)}return true}
function PC_addPopup(a){PC_assertIsPopup(a);var b=0;for(;b<gPopupController.activePopups_.length;++b)if(a===gPopupController.activePopups_[b])return false;gPopupController.activePopups_.push(a);return true}function PC_assertIsPopup(a){AssertType(a.deactivate,Function,"popup missing deactivate function")}var gPopupController=new PopupController,gPopupControllerInstalled=false;if(Array.prototype.indexOf==undefined)Array.prototype.indexOf=function(a){var b=0;for(;b<this.length;++b)if(this[b]==a)return b;return-1};function DIT_forceProperTableWidth(){var a=$("confirmarea");if(a)a.style.display="none"};function DIT_hideID(a){ShowElement($(a),false);return false}function DIT_showID(a){ShowElement($(a),true);return false}function DIT_hideEl(a){ShowElement(a,false);return false}function DIT_showEl(a){ShowElement(a,true);return false}function DIT_showInstead(a,b){ShowElement($(a),true);ShowElement(b,false);return false}
function DIT_showBelow(a,b,c,d){var e=$(a),f=nodeBounds(b),g=f.x,h=f.y+f.h;if(BR_IsIE()){h+=-2;g+=0}if(BR_IsSafari()){h+=3;g+=8}e.style.display="block";e.style.left="-2000px";if(a=="pop__dot")g=g-e.offsetWidth+b.offsetWidth;if(c)g+=c;if(d)h+=d;e.style.left=g+"px";e.style.top=h+"px";var i=new DIT_MyPopup(e);i.show();return false}
function DIT_showRight(a,b,c,d){var e=$(a),f=nodeBounds(b),g=f.x+f.w,h=f.y;if(BR_IsIE())g+=0;if(BR_IsNav()||BR_IsSafari())g+=2;e.style.left="-2000px";e.style.position="absolute";if(c)g+=c;if(d)h+=d;e.style.left=g+"px";e.style.top=h+"px";var i=new DIT_MyPopup(e);i.show();return false}function DIT_closePopup(a){var b=$(a);if(b)b.style.display="none"}var DIT_allColumnNames=[];
function DIT_closeAllPopups(a){var b=0;for(;b<DIT_allColumnNames.length;b++){DIT_closePopup("pop_"+b);DIT_closePopup("filter_"+b)}DIT_closePopup("pop__dot");RemoveClass(a,"hover");return false}function DIT_closeSubmenus(){var a=0;for(;a<DIT_allColumnNames.length;a++)DIT_closePopup("filter_"+a);return false}
function DIT_toggleHidden(a){for(;a;){if(HasClass(a,"closed")){RemoveClass(a,"closed");AddClass(a,"opened");return false}if(HasClass(a,"opened")){RemoveClass(a,"opened");AddClass(a,"closed");return false}a=a.parentNode}}function DIT_toggleCollapse(a){for(;a;){if(HasClass(a,"collapse")){RemoveClass(a,"collapse");AddClass(a,"expand");return false}if(HasClass(a,"expand")){RemoveClass(a,"expand");AddClass(a,"collapse");return false}a=a.parentNode}}
function DIT_showHidden(a){for(;a;){if(HasClass(a,"closed")){RemoveClass(a,"closed");AddClass(a,"opened");return false}if(HasClass(a,"opened"))return false;a=a.parentNode}}function DIT_toggleColumn(a){var b=$("colcontrol");HasClass(b,a)?RemoveClass(b,a):AddClass(b,a);return false}function DIT_toggleRows(a){var b=$("colcontrol");AddClass(b,"hide_pri_groups");AddClass(b,"hide_mile_groups");AddClass(b,"hide_stat_groups");DIT_toggleColumn(a);return false}
function DIT_rowRolloverOn(a){AddClass(a,"hover");return false}function DIT_rowRolloverOff(a){RemoveClass(a,"hover");return false}function DIT_MyPopup(a){this._div=a;this._isVisible=false}DIT_MyPopup.prototype.show=function(){this._div.style.display="block";this._isVisible=true;PC_addPopup(this)};DIT_MyPopup.prototype.hide=function(){this._div.style.display="none";this._isVisible=false};
DIT_MyPopup.prototype.deactivate=function(a){if(this._isVisible){var b=GetMousePosition(a);if(nodeBounds(this._div).contains(b))return false;else{this.hide();return true}}else return true};var DIT_rowToHighlight=undefined;function DIT_highlightRow(a){DIT_rowToHighlight=a;window.setTimeout("_highlightRowCallback()",10);return false}function DIT_highlightRowCallback(){var a=DIT_rowToHighlight,b=a.checked;for(;a&&a.tagName!="TR";)a=a.parentNode;b?AddClass(a,"selected"):RemoveClass(a,"selected")};function DIT_selectAllIssues(){DIT_selectIssues(true)}function DIT_selectNoneIssues(){DIT_selectIssues(false)}function DIT_selectIssues(a){var b=$("resultstable"),c=0;for(;c<b.rows.length;++c){var d=b.rows[c],e=d.cells[0];if(e.tagName=="TD"){var f=0;for(;f<e.childNodes.length;++f){var g=e.childNodes[f];if(g.tagName=="INPUT"&&g.type=="checkbox"){g.checked=a?"checked":"";a?AddClass(d,"selected"):RemoveClass(d,"selected")}}}}}var DIT_nextFileID=1;
function DIT_addAttachmentFields(a){if(!(DIT_nextFileID>=16)){var b=$(a);b.style.marginTop="4px";var c=document.createElement("div");c.innerHTML='<input type="file" name="file'+DIT_nextFileID+'" size=35 style="width:auto;margin-left:17px">&nbsp;<a style="font-size:x-small" href="#" onclick="this.parentNode.parentNode.removeChild(this.parentNode); return false">Remove</a> ';b.appendChild(c);++DIT_nextFileID;if(DIT_nextFileID<16)$("attachafile").innerHTML="Attach another file";else $("attachafile").innerHTML=
""}}function DIT_openIssueUpdateForm(a,b){DIT_showHidden($("makechangesarea"));DIT_goToAnchor("makechanges");$("addCommentTextArea").focus();DIT_fetchOptions(a,b);DIT_forceProperTableWidth()}var DIT_currentPromptIndex=0;
function DIT_selectPrompt(a){DIT_showHidden($("prompt_edit_panel"));DIT_currentPromptIndex=a.value;var b=$("prompt_text_editor");DIT_makeDefined(b);$("prompt_members_only_checkbox").checked=$("prompt_members_only_"+DIT_currentPromptIndex).value=="yes";$("prompt_summary_editor").value=$("prompt_summary_"+DIT_currentPromptIndex).value;$("prompt_summary_must_be_edited_checkbox").checked=$("prompt_summary_must_be_edited_"+DIT_currentPromptIndex).value=="yes";b.value=$("prompt_text_"+DIT_currentPromptIndex).value;
$("prompt_status_editor").value=$("prompt_status_"+DIT_currentPromptIndex).value;$("prompt_owner_editor").value=$("prompt_owner_"+DIT_currentPromptIndex).value;var c=0;for(;c<15;c++)$("prompt_label_editor"+c).value=$("prompt_label_"+DIT_currentPromptIndex+"_"+c).value;var d=0,c=0;for(;c<DIT_promptNames.length;c++)DIT_promptNames[c]!="<DELETED>"&&d++;if(d>1)$("delbtn").disabled="";else $("delbtn").disabled="disabled"}var DIT_promptNames=[];
function DIT_newPrompt(){var a=DIT_promptNames.length,b=prompt("Name of new template?","");b.replace(/[&<>"]/g,"");if(!!b){var c=0;for(;c<DIT_promptNames.length;c++)if(b==DIT_promptNames[c]){alert("Please choose a unique name.");return}DIT_addPromptHiddenFields(a,b);DIT_promptNames.push(b);$("prompt_menu").innerHTML+='<option value="'+a+'" selected=selected>'+b+"</select>";$("default_prompt_for_developers").innerHTML+='<option value="'+b+'">'+b+"</select>";$("default_prompt_for_users").innerHTML+=
'<option value="'+b+'">'+b+"</select>";DIT_selectPrompt($("prompt_menu"))}}
function DIT_addPromptHiddenFields(a,b){var c=[];DIT_pushHiddenField(c,"prompt_name_"+a,"prompt_name_"+a,b);DIT_pushHiddenField(c,"prompt_members_only_"+a);DIT_pushHiddenField(c,"prompt_summary_"+a);DIT_pushHiddenField(c,"prompt_summary_must_be_edited_"+a);DIT_pushHiddenField(c,"prompt_text_"+a);DIT_pushHiddenField(c,"prompt_status_"+a);DIT_pushHiddenField(c,"prompt_owner_"+a);DIT_pushHiddenField(c,"prompt_members_only_"+a);var d=0;for(;d<15;d++)DIT_pushHiddenField(c,"prompt_label_"+a,"prompt_label_"+
a+"_"+d);$("adminIssues").innerHTML+=c.join("")}function DIT_pushHiddenField(a,b,c,d){a.push('<input type=hidden name="',b,'"',' id="',c||b,'"',' value="',d||"",'"/>')}
function DIT_deletePrompt(){DIT_promptNames.splice(DIT_currentPromptIndex,1,"<DELETED>");$("prompt_name_"+DIT_currentPromptIndex).value="<DELETED>";DIT_toggleHidden($("prompt_edit_panel"));$("delbtn").disabled="disabled";DIT_rebuildPromptMenu();DIT_rebuildDefaultPromptMenu("default_prompt_for_developers");DIT_rebuildDefaultPromptMenu("default_prompt_for_users")}
function DIT_rebuildPromptMenu(){var a=[],b=0;for(;b<DIT_promptNames.length;b++)DIT_promptNames[b]!="<DELETED>"&&a.push("<option value="+b,">",DIT_promptNames[b],"</option>");$("prompt_menu").innerHTML=a.join("")}
function DIT_rebuildDefaultPromptMenu(a){var b=$(a).value,c=[],d=0;for(;d<DIT_promptNames.length;d++)if(DIT_promptNames[d]!="<DELETED>"){c.push('<option value="',DIT_promptNames[d],'"');b==DIT_promptNames[d]&&c.push(' selected="selected"');c.push(">",DIT_promptNames[d],"</option>")}$(a).innerHTML=c.join("")}
function DIT_switchPrompt(a,b){var c=true;if(DIT_isDirty)c=confirm("Switching to a different template will lose the text you entered.");if(c)window.location="/p/"+a+"/issues/entry?template="+b}function DIT_makeDefined(a){if(HasClass(a,"undef")){RemoveClass(a,"undef");a.value=""}}
function DIT_savePrompt(){if(DIT_currentPromptIndex){$("prompt_members_only_"+DIT_currentPromptIndex).value=$("prompt_members_only_checkbox").checked?"yes":"";$("prompt_summary_"+DIT_currentPromptIndex).value=$("prompt_summary_editor").value;$("prompt_summary_must_be_edited_"+DIT_currentPromptIndex).value=$("prompt_summary_must_be_edited_checkbox").checked?"yes":"";$("prompt_text_"+DIT_currentPromptIndex).value=$("prompt_text_editor").value;$("prompt_status_"+DIT_currentPromptIndex).value=$("prompt_status_editor").value;
$("prompt_owner_"+DIT_currentPromptIndex).value=$("prompt_owner_editor").value;var a=0;for(;a<15;a++)$("prompt_label_"+DIT_currentPromptIndex+"_"+a).value=$("prompt_label_editor"+a).value}}function DIT_toggleStar(a,b,c){var d=a.src.indexOf("star_off.gif")!=-1?1:0;a.src=d?"http://www.gstatic.com/codesite/ph/images/star_on.gif":"http://www.gstatic.com/codesite/ph/images/star_off.gif";DIT_setStar(c,b,d)}var DIT_starXmlHttp=undefined;
function DIT_setStar(a,b,c){DIT_starXmlHttp=XH_XmlHttpCreate();var d="/p/"+b+"/issues/setstar.do?alt=js&issueid="+a+"&starred="+c+"&cd="+(new Date).getTime();XH_XmlHttpGET(DIT_starXmlHttp,d,DIT_setStarCallback)}function DIT_setStarCallback(){DIT_starXmlHttp.readyState==4&&DIT_starXmlHttp.status==200&&DIT_gotSetStar(DIT_starXmlHttp.responseText)}function DIT_gotSetStar(a){_d=null;try{eval("_d="+a)}catch(b){alert("DIT: error parsing response of issue starring");return null}}
function DIT_toggleStarLocal(a,b){var c=a.src.indexOf("star_off.gif")!=-1?1:0;a.src=c?"http://www.gstatic.com/codesite/ph/images/star_on.gif":"http://www.gstatic.com/codesite/ph/images/star_off.gif";$(b).value=""+c}var DIT_isDirty=false;function DIT_dirty(){DIT_isDirty=true}function DIT_confirmDiscardUpdate(){if(!DIT_isDirty||confirm("Discard your changes?"))$("makechangesarea").className="closed"}
function DIT_confirmDiscardEntry(){if(!DIT_isDirty||confirm("Discard your changes?"))DIT_go("list")}
function DIT_exposeExistingLabelFields(a){if($("label"+a+"3").value||$("label"+a+"4").value||$("label"+a+"5").value)if($("addrow1")){DIT_showID(a+"row2");DIT_hideID("addrow1")}if($("label"+a+"6").value||$("label"+a+"7").value||$("label"+a+"8").value){DIT_showID(a+"row3");DIT_hideID("addrow2")}if($("label"+a+"9").value||$("label"+a+"10").value||$("label"+a+"11").value){DIT_showID(a+"row4");DIT_hideID("addrow3")}if($("label"+a+"12").value||$("label"+a+"13").value||$("label"+a+"14").value){DIT_showID(a+
"row5");DIT_hideID("addrow4")}}var DIT_firstEvent=true;function DIT_clearOnFirstEvent(){if(DIT_firstEvent){DIT_firstEvent=false;$("summary").value=""}}var DIT_novelStatuses=[],DIT_novelLabels=[];
function DIT_confirmNovelStatus(a){var b=a.value.trim().toLowerCase(),c=b!=="",d=DIT_statusWords,e=0;for(;e<d.length&&c;++e){var f=d[e];if(b==f.toLowerCase())c=false}if(c){DIT_novelStatuses.indexOf(a)==-1&&DIT_novelStatuses.push(a);AddClass(a,"novel");AddClass(a,"hasfocus")}else{DIT_novelStatuses.indexOf(a)!=-1&&DIT_novelStatuses.splice(DIT_novelStatuses.indexOf(a),1);RemoveClass(a,"novel")}DIT_updateConfirmBeforeSubmit();return true}
function DIT_confirmNovelLabel(a){var b=a.value.trim().toLowerCase();if(b.search("-")==0)b=b.substr(1);var c=b!=="",d=DIT_labelWords,e=0;for(;e<d.length&&c;++e){var f=d[e];if(b==f.toLowerCase())c=false}if(c){DIT_novelLabels.indexOf(a)==-1&&DIT_novelLabels.push(a);AddClass(a,"novel");AddClass(a,"hasfocus")}else{DIT_novelLabels.indexOf(a)!=-1&&DIT_novelLabels.splice(DIT_novelLabels.indexOf(a),1);RemoveClass(a,"novel")}DIT_updateConfirmBeforeSubmit();return true}
var DIT_usedPrefixes={},DIT_labelFieldIDPrefix="";function DIT_prepLabelAC(a){var b=0;for(;b<15;b++)DIT_validateLabel($(a+b))}function DIT_updateUsedPrefixes(a){a.oldPrefix!=undefined&&DeleteArrayElement(DIT_usedPrefixes[a.oldPrefix],a);var b=a.value.split("-")[0].toLowerCase();if(DIT_usedPrefixes[b]==undefined)DIT_usedPrefixes[b]=[a];else DIT_usedPrefixes[b].push(a);a.oldPrefix=b}
function DIT_highlightExclusiveLabelPrefixConflicts(){var a=[];for(var b in DIT_usedPrefixes){var c=DIT_usedPrefixes[b];if(c==undefined||c.length==0)delete DIT_usedPrefixes[b];else if(c.length>1&&FindInArray(DIT_exclPrefixes,b)!=-1){a.push(b);var d=0;for(;d<c.length;d++){var e=c[d];AddClass(e,"exclconflict")}}else{var d=0;for(;d<c.length;d++){var e=c[d];RemoveClass(e,"exclconflict")}}}if(a.length>0){var f=DIT_restrict_to_known?"Error":"Warning";$("confirmmsg").innerHTML=f+": Multiple values for: "+
a.join(", ");$("confirmarea").className="exclconflict";$("confirmarea").style.display=""}}function DIT_validateLabel(a){if(!(a==undefined)){DIT_confirmNovelLabel(a);DIT_updateUsedPrefixes(a);DIT_highlightExclusiveLabelPrefixConflicts()}}
function DIT_updateConfirmBeforeSubmit(){var a=DIT_restrict_to_known?"Error":"Note",b=DIT_restrict_to_known?"undefined":"uncommon",c="";if(DIT_novelStatuses.length>0&&DIT_novelLabels.length==1)c=a+": You are using an "+b+" status and an "+b+" label.";else if(DIT_novelStatuses.length>0&&DIT_novelLabels.length>1)c=a+": You are using an "+b+" status and "+DIT_novelLabels.length+" "+b+" labels.";else if(DIT_novelStatuses.length>0)c=a+": You are using an "+b+" status value.";else if(DIT_novelLabels.length==
1)c=a+": You are using an "+b+" label.";else if(DIT_novelLabels.length>1)c=a+": You are using "+DIT_novelLabels.length+" "+b+" labels.";$("confirmmsg").innerHTML=c;if(c!=""){$("confirmarea").className="novel";$("confirmarea").style.display=""}else $("confirmarea").style.display="none"}function DIT_MoreActions_onchange(a){switch(a.value){case "bulk":DIT_HandleBulkEdit();break;case "colspec":DIT_closeAllPopups(a);DIT_showID("columnspec");break}a.value="moreactions"}
function DIT_HandleBulkEdit(){var a=[],b=0;for(;b<issueIds.length;b++){var c=document.getElementById("cb_"+issueIds[b]);c&&c.checked&&a.push(issueIds[b])}if(a.length>0){var d=a.join(","),e="bulkedit?ids="+d;DIT_go(e+_ctx_args)}else alert("Please select some issues to edit")};var DIT_labelStore,DIT_exclPrefixes=[],DIT_statusStore,DIT_memberListStore,DIT_ownerStore,DIT_restrict_to_known;function DIT_fullComplete(a,b){if(!a.startsWith("*"))return null;var c=[],d=0;for(;d<b.length;d++)c.push(new _AC_Completion(b[d].name,b[d].name,b[d].doc));return c}
function DIT_openClosedComplete(a,b,c){if(!a.startsWith("*"))return null;var d=[];d.push({heading:"Open Statuses:"});var e=0;for(;e<b.length;e++)d.push(new _AC_Completion(b[e].name,b[e].name,b[e].doc));d.push({heading:"Closed Statuses:"});var e=0;for(;e<c.length;e++)d.push(new _AC_Completion(c[e].name,c[e].name,c[e].doc));return d}var DIT_statusWords=[];
function DIT_setUpStatusStore(a,b){var c={},d=0;for(;d<a.length;d++){var e=a[d];DIT_statusWords.push(e.name);c[e.name]=e.doc}var d=0;for(;d<b.length;d++){var e=b[d];DIT_statusWords.push(e.name);c[e.name]=e.doc}DIT_statusStore=new _AC_SimpleStore(DIT_statusWords);DIT_statusStore.docstrings=c;DIT_statusStore.commaCompletes=false;DIT_statusStore.substitute=function(g,h,i,j){return j.value};var f=true;DIT_statusStore.completable=function(g,h){if(g=="")return"*status";if(f){f=false;return"*status"}if(h==
g.length)return g;return"*status"};DIT_statusStore.completions=function(g,h){var i=DIT_openClosedComplete(g,a,b);if(i)return i;return _AC_SimpleStore.prototype.completions.call(this,g,h)}}
function DIT_setUpMemberStore(a){var b=[],c={},d=0;for(;d<a.length;d++){var e=a[d];b.push(e.name);c[e.name]=e.doc}DIT_memberListStore=new _AC_SimpleStore(b);DIT_memberListStore.docstrings=c;DIT_memberListStore.completions=function(f,g){var h=DIT_fullComplete(f,a);if(h)return h;return _AC_SimpleStore.prototype.completions.call(this,f,g)};DIT_memberListStore.completable=function(f,g){if(f=="")return"*member";return _AC_SimpleStore.prototype.completable.call(this,f,g)};DIT_ownerStore=new _AC_SimpleStore(b);
DIT_ownerStore.docstrings=c;DIT_ownerStore.commaCompletes=false;DIT_ownerStore.substitute=function(f,g,h,i){return i.value};DIT_ownerStore.completions=function(f,g){var h=DIT_fullComplete(f,a);if(h)return h;return _AC_SimpleStore.prototype.completions.call(this,f,g)};DIT_ownerStore.completable=function(f,g){if(f=="")return"*owner";if(g==f.length)return f;return"*owner"}}var DIT_labelWords=[];
function DIT_setUpLabelStore(a){var b={},c=0;for(;c<a.length;c++){var d=a[c];DIT_labelWords.push(d.name);b[d.name]=d.doc}DIT_labelStore=new _AC_SimpleStore(DIT_labelWords);DIT_labelStore.docstrings=b;DIT_labelStore.commaCompletes=false;DIT_labelStore.substitute=function(e,f,g,h){return h.value};DIT_labelStore.completable=function(e,f){if(f==0)return"*label";var g=0,h=f;for(;--h>=0;){var i=e.charAt(h);if(i==" "||i==","){g=h+1;break}}var j=e.substring(g,f);if(e.indexOf("-")>0)j=e.substring(g,Math.min(f,
e.indexOf("-")));return j};DIT_labelStore.completions=function(e,f){var g=DIT_fullComplete(e,a);if(g==null)g=_AC_SimpleStore.prototype.completions.call(this,e,f);var h=[],i=0;for(;i<g.length;i++){e=g[i].value.split("-")[0].toLowerCase();if(FindInArray(DIT_exclPrefixes,e)==-1||DIT_usedPrefixes[e]==undefined||DIT_usedPrefixes[e].length==0||DIT_usedPrefixes[e].length==1&&DIT_usedPrefixes[e][0]==ac_focusedInput){var j=true;for(var k in DIT_usedPrefixes){var l=DIT_usedPrefixes[k],m=0;for(;m<l.length;m++){var n=
l[m];if(n.value.toLowerCase()==g[i].value.toLowerCase()&&n!=ac_focusedInput)j=false}}j&&h.push(g[i])}}return h}}var DIT_optionsXmlHttp=undefined;function DIT_fetchOptions(a,b){DIT_optionsXmlHttp=XH_XmlHttpCreate();var c="/p/"+a+"/feeds/"+b+"?alt=js&cd="+(new Date).getTime();XH_XmlHttpGET(DIT_optionsXmlHttp,c,DIT_issueOptionsFeedCallback)}
function DIT_issueOptionsFeedCallback(){DIT_optionsXmlHttp.readyState==4&&DIT_optionsXmlHttp.status==200&&DIT_gotIssueOptionsFeed(DIT_optionsXmlHttp.responseText)}
function DIT_gotIssueOptionsFeed(a){_d=null;try{eval("_d="+a)}catch(b){alert("DIT: error parsing response of issue options");return null}DIT_setUpStatusStore(_d.open,_d.closed);DIT_setUpLabelStore(_d.labels);DIT_setUpMemberStore(_d.members);DIT_exclPrefixes=_d.excl_prefixes;DIT_prepLabelAC(DIT_labelFieldIDPrefix);DIT_restrict_to_known=_d.strict};function DIT_go(a){document.location=a}function DIT_goToAnchor(a){document.location.hash=a}function DIT_formatContextQueryArgs(a,b,c,d,e,f,g){var h="",i=_getElById("colspec").value;if(a!=2)h+="&can="+a;if(b!="")h+="&q="+b;if(c!="")h+="&sort="+c;if(i!=d)h+="&colspec="+i;if(e!=0)h+="&start="+e;if(f!=g)h+="&num="+f;return h}
function DIT_filterTo(a,b){var c=DIT_workAroundBrokenIEGetElementByID("q").value;if(c!="")c+=" ";c+=a+":"+b;var d="list?can="+$("can").value+"&q="+c;if($("sort")&&$("sort").value)d+="&sort="+$("sort").value;d+="&colspec="+$("colspec").value;DIT_go(d)}
function DIT_addSort(a,b){var c="";if($("sort"))c=$("sort").value;var d=c.split(/ +/),e=a;if(b)e="-"+a;var f=[e],g=0;for(;g<d.length;g++)d[g]!=""&&d[g]!=a&&d[g]!="-"+a&&f.push(d[g]);var h="list?can="+$("can").value+"&q="+DIT_workAroundBrokenIEGetElementByID("q").value;h+="&sort="+f.join("+");h+="&colspec="+$("colspec").value;DIT_go(h)}function DIT_sortUp(a){DIT_addSort(a,false)}function DIT_sortDown(a){DIT_addSort(a,true)}
function DIT_workAroundBrokenIEGetElementByID(a,b){b||(b="input");var c=document.getElementsByTagName(b),d=0;for(;d<c.length;d++)if(c.item(d).getAttribute("id")==a)return c.item(d);return null};function DIT_onload(){_ac_install();_ac_register(function(a){if(a.id.startsWith("label"))return DIT_labelStore;if(a.id.startsWith("status"))return DIT_statusStore;if(a.id.startsWith("member"))return DIT_memberListStore;if(a.id.startsWith("owner"))return DIT_ownerStore});_PC_Install();DIT_allColumnNames=_allColumnNames;DIT_labelFieldIDPrefix=_lfidprefix}_hideID=DIT_hideID;_showID=DIT_showID;_hideEl=DIT_hideEl;_showEl=DIT_showEl;_showInstead=DIT_showInstead;_selectAllIssues=DIT_selectAllIssues;
_selectNoneIssues=DIT_selectNoneIssues;_toggleHidden=DIT_toggleHidden;_toggleCollapse=DIT_toggleCollapse;_toggleRows=DIT_toggleRows;_toggleColumn=DIT_toggleColumn;_onload=DIT_onload;_MoreActions_onchange=DIT_MoreActions_onchange;_fetchOptions=DIT_fetchOptions;_openIssueUpdateForm=DIT_openIssueUpdateForm;_addAttachmentFields=DIT_addAttachmentFields;_acstore=_AC_SimpleStore;_accomp=_AC_Completion;_acreg=_ac_register;_go=DIT_go;_formatContextQueryArgs=DIT_formatContextQueryArgs;_ctx_args="";
_filterTo=DIT_filterTo;_sortUp=DIT_sortUp;_sortDown=DIT_sortDown;_closeAllPopups=DIT_closeAllPopups;_closeSubmenus=DIT_closeSubmenus;_showRight=DIT_showRight;_showBelow=DIT_showBelow;_highlightRow=DIT_highlightRow;_highlightRowCallback=DIT_highlightRowCallback;_selectPrompt=DIT_selectPrompt;_savePrompt=DIT_savePrompt;_newPrompt=DIT_newPrompt;_deletePrompt=DIT_deletePrompt;_switchPrompt=DIT_switchPrompt;_promptNames=DIT_promptNames;_toggleStar=DIT_toggleStar;_toggleStarLocal=DIT_toggleStarLocal;
_rowRolloverOn=DIT_rowRolloverOn;_rowRolloverOff=DIT_rowRolloverOff;_confirmNovelStatus=DIT_confirmNovelStatus;_confirmNovelLabel=DIT_confirmNovelLabel;_vallab=DIT_validateLabel;_dirty=DIT_dirty;_exposeExistingLabelFields=DIT_exposeExistingLabelFields;_confirmDiscardEntry=DIT_confirmDiscardEntry;_confirmDiscardUpdate=DIT_confirmDiscardUpdate;_lfidprefix=undefined;_clearOnFirstEvent=DIT_clearOnFirstEvent;_forceProperTableWidth=DIT_forceProperTableWidth;_RC=RemoveClass;_acof=_ac_onfocus;_acmo=_ac_mouseover;
_acse=_ac_select;_acrob=_ac_real_onblur;_allColumnNames=[];_getElById=DIT_workAroundBrokenIEGetElementByID;if(BR_hasExcessBlurEvents()){document.addEventListener("click",_ac_fake_onblur,false);document.captureEvents&&document.captureEvents(Event.CLICK)};function _ac_install(){ac_addHandler_(document.body,"onkeydown",ac_keyevent_);ac_addHandler_(document.body,"onkeypress",ac_keyevent_)}function _ac_register(a){var b=ac_storeConstructors.length;for(;--b>=0;)if(ac_storeConstructors[b]===a)return;ac_storeConstructors.push(a)}function _ac_onfocus(a){ac_keyevent_(a)}function _ac_isCompleting(){return!!ac_store&&!ac_suppressCompletions}
function _ac_isCompleteListShowing(){return!!ac_store&&!ac_suppressCompletions&&ac_completions&&ac_completions.length}function _ac_cancel(){ac_suppressCompletions=true;ac_updateCompletionList(false)}function ac_addHandler_(a,b,c){var d=a[b];a[b]=d?ac_fnchain_(a[b],c):c;return d}function ac_cancelEvent_(a){if("stopPropagation"in a)a.stopPropagation();else a.cancelBubble=true;"preventDefault"in a&&a.preventDefault()}
function ac_fnchain_(a,b){return function(){var c=a.apply(this,arguments),d=b.apply(this,arguments);return c===false||d===false?false:true}}
function ac_keyevent_(a){a=a||window.event;var b=a.target||a.srcElement;if("INPUT"==b.tagName&&b.type.match(/^text$/i)||"TEXTAREA"==b.tagName){var c=GetKeyCode(a),d=a.type=="keydown",e=a.shiftKey;if(b!==ac_focusedInput||ac_store===null){ac_focusedInput=b;var f=false;if(13!==c&&27!==c){var g=0;for(;g<ac_storeConstructors.length;++g){var h=ac_storeConstructors[g](b,a);if(h){ac_store=h;ac_oldBlurHandler=ac_addHandler_(ac_focusedInput,"onblur",_ac_ob);f=true;break}}if(!f){ac_focusedInput=null;_ac_ob(null)}}}if(ac_store){var i=
ac_store.isCompletionKey(c,d,e),j=ac_completions&&ac_completions.length>0,k=false;if(i&&j){k=!ac_suppressCompletions&&!!ac_completions;window.setTimeout(function(){ac_store&&ac_handleKey_(c,d,e)},0)}else if(i)ac_store.oncomplete&&ac_store.oncomplete(false,c,ac_focusedInput,undefined);else{k=c==27||c==40||c==38;window.setTimeout(function(){ac_store&&ac_handleKey_(c,d,e)},0)}k&&ac_cancelEvent_(a);return!k}}return true}function _ac_ob(a){BR_hasExcessBlurEvents()||_ac_real_onblur(a)}
function _ac_real_onblur(){if(ac_focusedInput)ac_focusedInput.onblur=ac_oldBlurHandler;ac_oldBlurHandler=ac_focusedInput=ac_store=null;ac_suppressCompletions=false;ac_updateCompletionList(false)}function _ac_fake_onblur(a){var b;if(!a)var a=window.event;if(a.target)b=a.target;else if(a.srcElement)b=a.srcElement;if(b.nodeType==3)b=b.parentNode;"INPUT"!=b.nodeName&&_ac_real_onblur(a)}function _AC_Store(){}_AC_Store.prototype.completable=function(){alert("UNIMPLEMENTED completable")};
_AC_Store.prototype.completions=function(){alert("UNIMPLEMENTED completions")};_AC_Store.prototype.oncomplete=function(){};_AC_Store.prototype.substitute=function(){alert("UNIMPLEMENTED substitute")};_AC_Store.prototype.commaCompletes=true;_AC_Store.prototype.isCompletionKey=function(a,b,c){if(!b&&(13===a||AC_COMMA_KEYCODE==a&&this.commaCompletes))return true;if(9===a&&!c)return false;return false};
function _AC_SimpleStore(a){this.firstCharMap_={};var b=0;for(;b<a.length;++b){var c=a[b];if(!!c){var d=c.split(/\W+/),e=0;for(;e<d.length;++e)if(d[e]){var f=d[e].charAt(0).toLowerCase(),g=this.firstCharMap_[f];if(g){if(g[g.length-1].value==c)continue}else g=this.firstCharMap_[f]=[];g.push(new _AC_Completion(c,null,""))}}}this.countThreshold=10;this.docstrings={}}_AC_SimpleStore.prototype=new _AC_Store;_AC_SimpleStore.prototype.constructor=_AC_SimpleStore;
_AC_SimpleStore.prototype.completable=function(a,b){var c=0,d=0,e=0;for(;e<b;++e){var f=a.charAt(e);switch(d){case 0:if('"'==f)d=1;else if(","==f)c=e+1;break;case 1:if('"'==f)d=0;break}}for(;c<b&&" \t\r\n".indexOf(a.charAt(c))>=0;)++c;return a.substring(c,b)};
_AC_SimpleStore.prototype.completions=function(a,b){if(!a)return[];var c=new RegExp("^(.*[\\s<\"',])?("+a.replace(/([\^*+\-\$\\\{\}\(\)\[\]\#?\.])/g,"\\$1")+")(.*)","i");if(!(b&&b.length)&&a)b=this.firstCharMap_[a.charAt(0).toLowerCase()];var d=[];if(b){var e=0;for(;e<b.length;++e){var f=b[e].value.match(c);if(f){d.push(new _AC_Completion(b[e].value,ac_preTextToHtml(f[1]||"")+"<b>"+ac_preTextToHtml(f[2])+"</b>"+ac_preTextToHtml(f[3]),this.docstrings[b[e].value]));if(d.length>this.countThreshold)break}}}return d};
function _AC_CompareACCompletion(a,b){var c=a.value.toLowerCase().replace(/^\W*/,""),d=b.value.toLowerCase().replace(/^\W*/,"");return a.value===b.value?0:c<d?-1:1}_AC_SimpleStore.prototype.substitute=function(a,b,c,d){return a.substring(0,b-c.length)+d.value+", "+a.substring(b)};function _AC_Completion(a,b,c){this.value=a;this.html=b;this.dochtml=c}_AC_Completion.prototype.toString=function(){return"(AC_Completion: "+this.value+")"};
var ac_storeConstructors=[],ac_focusedInput=null,ac_store=null,ac_oldBlurHandler=null,ac_suppressCompletions=false,ac_lastCompletable=null,ac_completions=null,ac_selected=-1;
function ac_handleKey_(a,b,c){ac_checkCompletions();var d=true,e=ac_completions?ac_completions.length:0;if(ac_store.isCompletionKey(a,b,c)){if(ac_selected<0&&e>=1)ac_selected=0;if(ac_selected>=0){var f=ac_focusedInput,g=ac_completions[ac_selected].value;ac_complete();ac_store.oncomplete&&ac_store.oncomplete(true,a,f,g)}}else switch(a){case 27:ac_selected=-1;d=false;break;case 38:if(b)ac_selected=Math.max(e>=0?0:-1,ac_selected-1);break;case 40:if(b)ac_selected=Math.min(e-1,ac_selected+1);break}ac_focusedInput&&
ac_updateCompletionList(d)}function _ac_select(a){ac_selected=a;ac_complete();ac_store.oncomplete&&ac_store.oncomplete(true,null,ac_focusedInput,ac_focusedInput.value);ac_checkCompletions();ac_updateCompletionList(true)}function _ac_mouseover(a){ac_selected=a;ac_updateCompletionList(true)}
function ac_complete(){var a=ac_getCaretPosition_(ac_focusedInput);ac_focusedInput.value=ac_store.substitute(ac_focusedInput.value,a,ac_lastCompletable,ac_completions[ac_selected]);ac_selected=-1;ac_lastCompletable=ac_completions=null;SetCursorPos(window,ac_focusedInput,ac_focusedInput.value.length)}
function ac_checkCompletions(){if(ac_suppressCompletions){ac_completions=ac_lastCompletable=null;ac_selected=-1}else{var a=ac_getCaretPosition_(ac_focusedInput),b=ac_store.completable(ac_focusedInput.value,a);if(!(b==ac_lastCompletable)){var c;if(ac_lastCompletable&&ac_lastCompletable.length<b.length&&b.substring(0,ac_lastCompletable.length)==ac_lastCompletable)c=ac_completions;else{ac_completions=null;ac_selected=-1}var d=ac_selected>=0?ac_completions[ac_selected].value:null;ac_completions=ac_store.completions(b,
c);ac_selected=-1;var e=0;for(;e<ac_completions.length;++e)if(d==ac_completions[e].value){ac_selected=e;break}ac_lastCompletable=b}}}
function ac_updateCompletionList(a){var b=document.getElementById("ac-list");if(a&&ac_completions&&ac_completions.length){if(!b){b=document.createElement("DIV");b.id="ac-list";b.style.position="absolute";b.style.display="none";document.body.appendChild(b)}if(ac_selected<0)ac_selected=0;var c=[],d=0;c.push("<table cellpadding=0 cellspacing=0>");var e=0;for(;e<ac_completions.length;++e)if(ac_completions[e].heading){c.push("<tr><th colspan=2>");d&&c.push("<br/>");c.push(ac_completions[e].heading,"</th></tr>");
d++}else{var f="onmousedown";if(navigator.userAgent.toLowerCase().indexOf("webkit")!=-1)f="onmouseup";c.push("<tr ",f,'="try{_acse(',e,')}finally{return false}"','onmouseover="_acmo(',e,')"',e==ac_selected?" class=selected>":">","<td>","&nbsp;",ac_completions[e].html);c.push("</td><td>&nbsp;");ac_completions[e].dochtml&&c.push("= ",ac_completions[e].dochtml);c.push("</td></tr>")}c.push("</table>");b.innerHTML=c.join("");var g=nodeBounds(ac_focusedInput);b.style.left=g.x+"px";b.style.top=g.y+g.h+"px";
b.style.display=""}else if(b){b.style.display="none";b.innerHTML=""}}function ac_preTextToHtml(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/\"/g,"&quot;").replace(/ /g,"&nbsp;").replace(/\r\n?|\n/g,"<br>")}
function ac_getCaretPosition_(a){if("INPUT"==a.tagName){var b=a.value.length;if(undefined!=a.selectionStart){b=a.selectionEnd;if(a.id.startsWith("status"))b=a.selectionStart}else if(document.selection){var c=document.selection.createRange(),d=c.text.length;c.moveStart("character",-b);b=c.text.length;if(a.id.startsWith("status"))b=c.text.length-d}return b}else return GetCursorPos(window,a)}var AC_COMMA_KEYCODE=",".charCodeAt(0);
function BR_hasExcessBlurEvents(){return navigator.userAgent.toLowerCase().indexOf("webkit")!=-1};
})()
